### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by mhintz**
Fixes compile warnings

### CODE REVIEW

**Comment by bjz** [comment]
Shall we do a release now?

**Comment by mhintz** [comment]
It seems like a lot has changed since 0.9.1, I'm in favor. I've been running off of my local master branch for a while. It would be 0.10.0 right?

Mark

**Comment by mhintz** [comment]
Adding a bump here, because this is the last place where a release was mentioned. Enough has changed that I think we should release 0.10.0. I'm using the master branch in my own projects, and it's a bit tricky to manage the dependencies of other libraries which depend on cgmath...

**Comment by bjz** [comment]
Oh woops, sorry. I was working on trying to get the new transformation API working, but the type system kept exploding. I'm thinking I might cherry pick the most important stuff for the next release.

**Comment by mhintz** [comment]
So, just to be clear, including the changes to the Transform trait would require solving #354, #355, #349, and doing something wrt #143 and #194, right?

(And, unless I'm mistaken, it would enable closing #61?)

**Comment by bjz** [comment]
You got it!

Just published v0.10.0 btw.

**Comment by mhintz** [comment]
Yay! \o/

Mark

**Pull request merged**
